// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeoqhdbadpbcblxwvzoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllb3FoZGJhZHBiY2JseHd2em9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTczNjYsImV4cCI6MjA1NzkzMzM2Nn0.hKkfmVdX4DGFnGyMHwNC94dw_fCqRUeyM_K-kRaaK84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);